free_throttled_rate: 1.0 # [Hz]
occupied_throttled_rate: 1.0 # [Hz]

occupied:
  cube_size_factor: 1.0
  min_z: -1.79769e+308
  max_z: 1.79769e+308

free_space:
  publish: true
  cube_size_factor: 0.3
  color:
    r: 0.0
    g: 1.0
    b: 0.0
    a: 0.4

height_map:
  enabled: true
  color_factor: 0.8
  color:
    r: 1.0
    g: 0.0
    b: 0.0
    a: 1.0

colored_map:
  enabled: false
